# Generated by Django 4.1.3 on 2023-03-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeneficiaryType', models.CharField(choices=[('Primary', 'Primary_Beneficiary'), ('Contingent', 'Contingent_Benficiary')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationLevel', models.CharField(choices=[('Elementaty', 'Elementary'), ('HighSchool', 'HighSchool'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthStatus', models.CharField(choices=[('Healthy', 'Healthy'), ('UnHealthy', 'UnHealthy')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('HouseHoldIdNumber', models.CharField(max_length=40)),
                ('MaleMemberSize', models.IntegerField(null=True)),
                ('FemaleMemberSize', models.IntegerField(null=True)),
                ('NumberOfParticipatingMale', models.IntegerField(null=True)),
                ('NumberOfParticipatingFemale', models.IntegerField(null=True)),
                ('NumberOfMaleBody', models.IntegerField(null=True)),
                ('NumberOfFemaleBody', models.IntegerField(null=True)),
                ('RegistrationDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseholdProgram', models.CharField(choices=[('Childcare', 'Childcare'), ('disabled', 'Disabled'), ('Dependent', 'Dependent'), ('cleaning', 'Cleaning'), ('Meal preparation', 'Meal Preparation')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaritialStatus', models.CharField(choices=[('single', 'single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('HouseholdMemberIdNumber', models.CharField(max_length=40)),
                ('NationalMemberIdNumber', models.CharField(max_length=40)),
                ('FirstName', models.CharField(max_length=40)),
                ('FatherName', models.CharField(max_length=40)),
                ('GrandFatherName', models.CharField(max_length=40)),
                ('MotherFullName', models.CharField(max_length=40)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('RegistrationDate', models.DateField(blank=True, null=True)),
                ('BeneficiaryType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.beneficiarytype')),
                ('EducationLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.educationlevel')),
                ('HealthStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.healthstatus')),
                ('Household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.household')),
                ('MaritialStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.maritialstatus')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='HouseHoldProgram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.householdprogram'),
        ),
    ]
